-- DQA_/HSROM/SCREENCOV_SCREENISOSTATE
CREATE OR REPLACE VIEW kis."DQA_/HSROM/SCREENCOV_SCREENISOSTATE"
  AS
  SELECT count(n.FALNR) AS "QUANTITY",
    CASE
      WHEN n."SCREENISOSTATE" ~ '\w' THEN n."SCREENISOSTATE"
        ELSE NULL
    END AS "SCREENISOSTATE",
    m.long_name
  FROM kis."/HSROM/SCREENCOV" n
  LEFT JOIN metadata_repository.TABLE m ON n."SCREENISOSTATE" = m.sourceid
  GROUP BY n."SCREENISOSTATE", m.long_name
  ORDER BY (count(n."FALNR")) DESC;

