-- DQA_/HSROM/SCREENCOV_SCREENVACCINE
CREATE OR REPLACE VIEW kis."DQA_/HSROM/SCREENCOV_SCREENVACCINE"
  AS
  SELECT count(n.FALNR) AS "QUANTITY",
    CASE
      WHEN n."SCREENVACCINE" ~ '\w' THEN n."SCREENVACCINE"
        ELSE NULL
    END AS "SCREENVACCINE",
    m.long_name
  FROM kis."/HSROM/SCREENCOV" n
  LEFT JOIN metadata_repository.TABLE m ON n."SCREENVACCINE" = m.sourceid
  GROUP BY n."SCREENVACCINE", m.long_name
  ORDER BY (count(n."FALNR")) DESC;

