-- DQA_/HSROM/SCREENCOV_DISSCREENDLLENTRY
CREATE OR REPLACE VIEW kis."DQA_/HSROM/SCREENCOV_DISSCREENDLLENTRY"
  AS
  SELECT count(n.FALNR) AS "QUANTITY",
    CASE
      WHEN n."DISSCREENDLLENTRY" ~ '\w' THEN n."DISSCREENDLLENTRY"
        ELSE NULL
    END AS "DISSCREENDLLENTRY",
    m.long_name
  FROM kis."/HSROM/SCREENCOV" n
  LEFT JOIN metadata_repository.TABLE m ON n."DISSCREENDLLENTRY" = m.sourceid
  GROUP BY n."DISSCREENDLLENTRY", m.long_name
  ORDER BY (count(n."FALNR")) DESC;

