-- DQA_/HSROM/SCREENCOV_SCREENOPTION
CREATE OR REPLACE VIEW kis."DQA_/HSROM/SCREENCOV_SCREENOPTION"
  AS
  SELECT count("RetrievalDate") AS "QUANTITY",
    CASE
      WHEN n."SCREENOPTION" ~ '\w' THEN n."SCREENOPTION"
        ELSE NULL
    END AS "SCREENOPTION"/*,
    m.long_name*/
  FROM kis."/HSROM/SCREENCOV" n
  --LEFT JOIN metadata_repository.TABLE m ON n."SCREENOPTION" = m.sourceid
  GROUP BY n."SCREENOPTION"--, m.long_name
  ORDER BY "QUANTITY" DESC;

