-- KIS."NBEW" DEFINITION

-- DROP TABLE

 DROP TABLE KIS."NBEW";

CREATE TABLE KIS."NBEW" (
	"EINRI"  VARCHAR(4) NOT NULL,
	"FALNR"  VARCHAR NOT NULL,
	"LFDBEW"  INT4 NOT NULL,
--	LFDNR  INT4 NOT NULL,
	"BEWTY"  BPCHAR(1) NULL,
	"BWART"  VARCHAR(2) NULL,
	"BWIDT"  DATE NULL,
	"BWIZT"  TIME NULL,
	"PLANB"  BOOL NULL,
	"STATU"  VARCHAR(2) NULL,
	"BWEDT"  DATE NULL,
	"BWEZT"  TIME NULL,
	"PLANE"  BOOL NULL,
	"LFDREF"  INT4 NULL,
	"NOTKZ"  BOOL NULL,
	"UNFKZ"  VARCHAR(3) NULL,
	"ORGFA"  VARCHAR(8) NULL,
	"ORGPF"  VARCHAR(8) NULL,
	"ZIMMR"  VARCHAR(8) NULL,
	"BETT"  VARCHAR(8) NULL,
	"PLANR"  VARCHAR(10) NULL,
	"ORGAU"  VARCHAR(8) NULL,
	"EZUST"  VARCHAR(2) NULL,
	"TODUR"  VARCHAR(3) NULL,
	"ERDAT"  DATE NULL,
	"UPDAT"  DATE NULL,
	"STORN"  BOOL NULL,
	"STDAT"  DATE NULL,
	"BEKAT"  VARCHAR(6) NULL,
	"NFGREF"  INT4 NULL,
	"VGNREF"  INT4 NULL,
	"STOID"  VARCHAR(3) NULL,
	"DSPTY"  VARCHAR(8) NULL,
	"VISTY"  VARCHAR(1) NULL,
	"BWGR1"  VARCHAR(2) NULL,
	"BWGR2"  VARCHAR(2) NULL,
	"TPART"  VARCHAR(2) NULL,
	"UNFVS"  BOOL NULL,
	"INSEV"  VARCHAR(4) NULL,
	"OPART"  VARCHAR(2) NULL,
	"CLASS" VARCHAR(4) NULL,
	"RFSRC"  VARCHAR(2) NULL,
	"FACHR"  VARCHAR(4) NULL,
	"UNFRT"  VARCHAR(4) NULL,
	"UNFAV"  VARCHAR(2) NULL,
	"RETRIEVALDATE"  TIMESTAMP NULL,
	PRIMARY KEY ("EINRI", "FALNR", "LFDBEW")
);

/*ALTER TABLE KIS."NBEW" 
  ADD COLUMN "BWPDT" DATE,
  ADD "BWPZT" TIME
;*/

-- KIS."NDIA" DEFINITION

-- DROP TABLE

-- DROP TABLE KIS."NDIA";

CREATE TABLE KIS."NDIA" (
	"EINRI"  VARCHAR(4) NOT NULL,
	"FALNR"  VARCHAR NOT NULL,
	"LFDNR"  INT4 NOT NULL,
	"LFDBEW"  INT4 NULL,
	"DKAT1"  VARCHAR(2) NULL,
	"DKEY1"  VARCHAR(30) NULL,
	"DKAT2"  VARCHAR(2) NULL,
	"DKEY2"  VARCHAR(30) NULL,
	"DKAT_REF"  VARCHAR(2) NULL,
	"DKEY_REF"  VARCHAR(30) NULL,
	"DIADT"  DATE NULL,
	"DIAZT"  TIME NULL,
	"ANZOP"  INT2 NULL,
	"EWDIA"  BOOL NULL,
	"BHDIA"  BOOL NULL,
	"AFDIA"  BOOL NULL,
	"ENDIA"  BOOL NULL,
	"FHDIA"  BOOL NULL,
	"KHDIA"  BOOL NULL,
	"OPDIA"  BOOL NULL,
	"SPERR"  BOOL NULL,
	"DIASI"  VARCHAR(1) NULL,
	"ERDAT"  DATE NULL,
	"UPDAT"  DATE NULL,
	"STORN"  BOOL NULL,
	"STDAT"  DATE NULL,
	"ARDIA"  BOOL NULL,
	"PODIA"  BOOL NULL,
	"TUDIA"  BOOL NULL,
	"DIABZ"  BOOL NULL,
	"DIAPR"  VARCHAR(1) NULL,
	"DIAGW"  VARCHAR(2) NULL,
	"DIAZS"  VARCHAR(2) NULL,
	"DIALO"  VARCHAR(2) NULL,
	"DIAFP"  VARCHAR(8) NULL,
	"DRG_DIA_SEQNO"  INT4 NULL,
	"DRG_CATEGORY"  VARCHAR(1) NULL,
	"DRG_RELVANT"  BOOL NULL,
	"DTYP1"  VARCHAR(1) NULL,
	"DTYP2"  VARCHAR(1) NULL,
	"DTYPE_REF"  VARCHAR(1) NULL,
	"DIA_LINK"  INT4 NULL,
	"CCL"  INT2 NULL,
	"DIA_VALDT"  DATE NULL,
	"DIA_PIA_SOM"  BOOL NULL,
	"RETRIEVALDATE"  TIMESTAMP NULL,
	CONSTRAINT PK_EINRI_FALNR_LFDNR PRIMARY KEY (EINRI, FALNR, LFDNR)
);

-- KIS."NFAL" DEFINITION

-- DROP TABLE

-- DROP TABLE KIS."NFAL";

CREATE TABLE KIS."NFAL" (
	"EINRI"  VARCHAR(4) NOT NULL,
	"FALNR"  VARCHAR NOT NULL,
	"FALAR"  VARCHAR(1) NULL,
	"PATNR"  VARCHAR NULL,
	"BEKAT"  VARCHAR(6) NULL,
	"ABRKZ"  VARCHAR(1) NULL,
	"SICHV"  BOOL NULL,
	"STATU"  VARCHAR(1) NULL,
	"NOTAN"  BOOL NULL,
	"KRZAN"  BOOL NULL,
	"ENDAT"  DATE NULL,
	"FGTYP"  VARCHAR(1) NULL,
	"KZKOM"  BOOL NULL,
	"ENDDT"  DATE NULL,
	"ERDAT"  DATE NULL,
	"UPDAT"  DATE NULL,
	"STORN"  BOOL NULL,
	"STDAT"  DATE NULL,
	"BEGDT"  DATE NULL,
	"FATYP"  VARCHAR(2) NULL,
	"FACHR"  VARCHAR(4) NULL,
	"ENDTYP"  VARCHAR(2) NULL,
	"PATW"  BOOL NULL,
	"PATGEW"  NUMERIC(7,3) NULL,
	"GWEIN"  VARCHAR(3) NULL,
	"PATGRO"  NUMERIC(5,2) NULL,
	"GREIN"  VARCHAR(3) NULL,
	"RESP"  INT4 NULL,
	"DELGW"  INT2 NULL,
	"SAPS_C"  INT2 NULL,
	"PIM2_C"  INT2 NULL,
	"CRIB_C"  INT2 NULL,
	"NEMS_C"  INT4 NULL,
	"SAPS_IMC"  INT2 NULL,
	"PIM2_IMC"  INT2 NULL,
	"CRIB_IMC"  INT2 NULL,
	"NEMS_IMC"  INT4 NULL,
	"RESPI_IMC"  INT4 NULL,
	"READM"  BOOL NULL,
	"RETRIEVALDATE"  TIMESTAMP NULL,
	CONSTRAINT PK_EINRI_FALNR PRIMARY KEY (EINRI, FALNR)
);

ALTER TABLE KIS."NFAL" 
  ADD COLUMN EINZG VARCHAR(10),
  ADD COLUMN INFKZ  BOOLEAN,
  ADD COLUMN ENTIM TIME
;

-- KIS."NICP" DEFINITION

-- DROP TABLE

-- DROP TABLE KIS."NICP";

CREATE TABLE KIS."NICP" (
	"EINRI"  VARCHAR(4) NOT NULL,
	"FALNR"  VARCHAR NOT NULL,
	"LNRIC"  VARCHAR(10) NOT NULL,
	"LFDBEW"  INT4 NULL,
	"ICPMK"  VARCHAR(2) NULL,
	"ICPML"  VARCHAR(10) NULL,
	"ICPHC"  BOOL NULL,
	"ANZOP"  INT2 NULL,
	"BGDOP"  DATE NULL,
	"BZTOP"  TIME NULL,
	"EZTOP"  TIME NULL,
	"LSLOK"  VARCHAR(2) NULL,
	"OPART"  VARCHAR(2) NULL,
	"UPDAT"  DATE NULL,
	"STORN"  BOOL NULL,
	"STDAT"  DATE NULL,
	"DRG_CATEGORY"  VARCHAR(1) NULL,
	"DRG_RELEVANT"  BOOL NULL,
	"ORGFA"  VARCHAR(8) NULL,
	"ORGPF"  VARCHAR(8) NULL,
	"ENDOP"  DATE NULL,
	"PRTYP"  VARCHAR(2) NULL,
	"QUANTITY"  NUMERIC(20,8) NULL,
	"UNIT"  VARCHAR(3) NULL,
	"CCL"  VARCHAR(3) NULL,
	"OPLEBSPEN"  BOOL NULL,
	"RETRIEVALDATE"  TIMESTAMP NULL,
	CONSTRAINT PK_EINRI_FALNR_LNRIC PRIMARY KEY (EINRI, FALNR, LNRIC)
);

ALTER TABLE KIS."NICP" 
  ADD COLUMN LNRIC_REF VARCHAR(11)
;

-- KIS."NPAT" DEFINITION

-- DROP TABLE

-- DROP TABLE KIS."NPAT";

CREATE TABLE KIS."NPAT" (
	"EINRI"  VARCHAR(4) NOT NULL,
	"PATNR"  VARCHAR NOT NULL,
	"GSCHL"  BPCHAR(1) NULL,
	"GBDAT"  INT2 NULL,
	"TODKZ"  BOOL NULL,
	"TODDT"  DATE NULL,
	"TODZT"  TIME NULL,
	"TODDB"  DATE NULL,
	"TODZB"  TIME NULL,
	"TODUR"  VARCHAR(3) NULL,
	"LAND"  BPCHAR(3) NULL,
	"PSTLZ"  VARCHAR NULL,
	"ERDAT"  DATE NULL,
	"UPDAT"  DATE NULL,
	"STORN"  BOOL NULL,
	"STDAT"  DATE NULL,
	"RACE"  VARCHAR NULL,
	"RETRIEVALDATE"  TIMESTAMP NULL,
	CONSTRAINT PK_EINRI_PATNR PRIMARY KEY (EINRI, PATNR)
);

ALTER TABLE KIS."NPAT" 
  ADD COLUMN STATU VARCHAR(2),
  ADD COLUMN GEBIE VARCHAR(10),
  ADD COLUMN RFPAT VARCHAR,
  ADD COLUMN UNKNOWN_GBDAT BOOLEAN,
  ADD COLUMN SEX_SPECIAL VARCHAR(2)
;


CREATE TABLE KIS."NV_PERIOD"(
  "EINRI"  VARCHAR(5) NOT NULL,
  "PATNR"  VARCHAR(11) NOT NULL,
  "FALNR"  VARCHAR NOT NULL,
  "FNAME"  VARCHAR(31) NOT NULL,
  "LFDNR"  INT NOT NULL,      
  "VALUE"  VARCHAR,  
  "DECLARE_DATE"  DATE,     
  "PERIOD_BEGDT"  DATE,     
  "PERIOD_ENDDT"  DATE,     
  "PERIOD_BEM"  VARCHAR(30),
  "ERDAT"  DATE,     
  "UPDAT"  DATE,     
  "STORN"  BOOLEAN,  
  "STDAT"  DATE,     
  "RETRIEVALDATE"  TIMESTAMP,
  "PRIMARY"  KEY (EINRI, PATNR, FNAME, LFDNR)
);



CREATE TABLE KIS."NPER"(
  "PERNR"  VARCHAR(11) PRIMARY KEY,
  "MAKZ"  BOOLEAN,  
  "ARZT"  BOOLEAN,  
  "PFLEG"  BOOLEAN,  
  "BARZT"  BOOLEAN,  
  "BEGDT"  DATE,     
  "ENDDT"  DATE,     
  "LOEKZ"  BOOLEAN,  
  "LODAT"  DATE,     
  "ERDAT"  DATE,     
  "UPDAT"  DATE,     
  "FACHR"  VARCHAR(5),
  "SPTYP"  VARCHAR(4),
  "RETRIEVALDATE"  TIMESTAMP
);
