DROP TABLE IF EXISTS kis.NVAC CASCADE;
CREATE TABLE kis.NVAC(
  MAND	VARCHAR(4),
  EINRI	VARCHAR(5),
  FALNR	VARCHAR(11),
  SETDATE	DATE,
  SETTIME	TIME,
  SCREENOPTION	VARCHAR(3),
  DISSCREENRESULT	VARCHAR(100),
  SCREENTESTTYPE	VARCHAR(3),
  SCREENSTATE	VARCHAR(10),
  SCREENISO	VARCHAR(3),
  SCREENISOSTATE	VARCHAR(6),
  SCREENOTHERS	VARCHAR(3),
  SCREENVACCSTAT	VARCHAR(3),
  SCREENVACCINE	VARCHAR(4),
  SCREENVACCDOSE	NUMERIC,
  INSDAT	DATE,
  INSTIM	TIME,
  PATNR	VARCHAR(11),
  RISKPAT	VARCHAR(2), -- BOOLEAN
  STORN	VARCHAR(2), --BOOLEAN
  STDAT	DATE,
  STTIM	TIME,
  LFDBEW	NUMERIC,
  RETRIEVALDATE TIMESTAMP not null,
  PRIMARY KEY (MAND, EINRI, FALNR, SETDATE, SETTIME, SCREENOPTION)
);
