drop table if exists metadata_repository.units;

create table metadata_repository.units(
  id serial primary key,
  sourceid varchar not null,
  sourceunit varchar not null,
  unitName varchar not null,
  unitid varchar,
  dimention varchar,
  description varchar,
  "source" varchar not null default 'kis' references metadata_repository.sources(sourceid),
  inserted timestamp not null default now(),
  unique(sourceid, sourceunit)
);


truncate table metadata_repository.units restart identity;
insert into metadata_repository.units (sourceid, sourceunit, unitName, unitid, dimention)
  values 
    ('"2', '"2', 'Quadratzoll', '"^2', 'Fläche'),
    ('CM3', 'CM3', 'Kubikzentimeter', 'cm^3', 'Volumen'),
    ('BAR', 'BAR', 'Bar', 'bar', 'Druck'),
    ('PMI', 'PMI', '1/Minute', '1/min', 'Frequenz'),
    ('AGE', 'AGE', 'Abgabeeinheit Klinikum', null, 'dimensionslos'),
    ('IE', 'IE', 'internationale Einheiten', null, 'dimensionslos'),
    ('INF', 'INF', 'Infusion', null, 'dimensionslos'),
    ('J/N', 'J/N', 'Ja/Nein', null, 'dimensionslos'),
    ('KAN', 'KAN', 'Kanister', null, 'dimensionslos'),
    ('KAR', 'KAR', 'Karton', null, 'dimensionslos'),
    ('TRT', 'TRT', 'Torte', null, 'dimensionslos'),
    ('TST', 'TST', 'Tests', null, 'dimensionslos'),
    ('TTE', 'TTE', 'Tüte', null, 'dimensionslos'),
    ('TUB', 'TUB', 'Tube', null, 'dimensionslos'),
    ('UN', 'UN', 'Units', null, 'dimensionslos'),
    ('VAL', 'VAL', 'Wertartikel', null, 'dimensionslos'),
    ('VE', 'VE', 'Verpackungseinheit', null, 'dimensionslos'),
    ('KI', 'KI', 'Kiste', null, 'dimensionslos'),
    ('KIE', 'KIE', 'Tausend internation. Einheiten', null, 'dimensionslos'),
    ('KP', 'KP', 'Klinikpackung', null, 'dimensionslos'),
    ('KPS', 'KPS', 'Kapsel', null, 'dimensionslos'),
    ('KRT', 'KRT', 'Karton', null, 'dimensionslos'),
    ('KS', 'KS', 'Kasten', null, 'dimensionslos'),
    ('KT', 'KT', 'Kit', null, 'dimensionslos'),
    ('KWK', 'KWK', 'kg Wirkstoff / kg', null, 'dimensionslos'),
    ('LE', 'LE', 'Leistungseinheit', null, 'dimensionslos'),
    ('LEH', 'LEH', 'Leistungseinheit', null, 'Zeit'),
    ('BG', 'BG', 'Bogen', null, 'dimensionslos'),
    ('EA', 'EA', 'Each', null, 'dimensionslos'),
    ('GL', 'GL', 'Glas', null, 'dimensionslos'),
    ('LVS', 'LVS', 'LVS Einheit Klinikum', null, 'dimensionslos'),
    ('M%', 'M%', 'Massenprozent', null, 'Massenverhältnis'),
    ('M%O', 'M%O', 'Massenpromille', null, 'Massenverhältnis'),
    ('ME', 'ME', 'Mengeneinheit (UKM)', null, 'dimensionslos'),
    ('MIE', 'MIE', 'Millionen intern Einheiten', null, 'dimensionslos'),
    ('MLW', 'MLW', 'Milliliter Wirkstoff', null, 'dimensionslos'),
    ('MMA', 'MMA', 'Millimeter/Jahr', null, 'Geschwindigkeit'),
    ('%', '%', 'Prozent', '%', 'Verhältnis'),
    ('°C', '°C', 'Grad Celsius', '°C', 'Temperatur'),
    ('°F', '°F', 'Fahrenheit', '°F', 'Temperatur'),
    ('C3S', 'C3S', 'Kubikzentimeter/Sekunde', 'cm^3/s', 'Volumenstrom'),
    ('"3', '"3', 'Kubikzoll', '"3', 'Volumen'),
    ('DM3', 'DM3', 'Kubikdezimeter', 'dm^3', 'Volumen'),
    ('FT3', 'FT3', 'Kubikfuß', 'ft^3', 'Volumen'),
    ('CM2', 'CM2', 'Quadratzentimeter', 'cm^2', 'Fläche'),
    ('FT2', 'FT2', 'Quadratfuß', 'ft^2', 'Fläche'),
    ('J', 'J', 'Joule', 'J', 'Energie'),
    ('MOL', 'MOL', 'Mol', 'mol', 'Molmenge'),
    ('JMO', 'JMO', 'Joule/Mol', 'J/mol', 'Molare Energie'),
    ('JKG', 'JKG', 'Joule/Kilogramm', 'J/kg', 'Spezifische Energie'),
    ('KML', 'KML', 'Kilomol', 'kmol', 'Molmenge'),
    ('KJM', 'KJM', 'Kilojoule/Mol', 'kJ/mol', 'Molare Energie'),
    ('LMS', 'LMS', 'Liter/Molsekunde', 'l/mol.s', 'Hydrolysegeschwind.'),
    ('KGM', 'KGM', 'Kilogramm/Mol', 'kg/mol', 'Molmasse'),
    ('MOK', 'MOK', 'Mol/Kilogramm', 'mol/kg', 'Spez Äquivalentmenge'),
    ('MMO', 'MMO', 'Millimol', 'mmol', 'Molmenge'),
    ('MMK', 'MMK', 'Millimol/Kilogramm', 'mmol/kg', 'Spez Äquivalentmenge'),
    ('KBK', 'KBK', 'Kilobecquerel/Kilogramm', 'kBq/kg', 'Spez Akt radioak Sub'),
    ('KGK', 'KGK', 'Kilogramm/Kilogramm', 'kg/kg', 'Massenverhältnis'),
    ('KGS', 'KGS', 'Kilogramm/Sekunde', 'kg/s', 'Massenstrom'),
    ('HPA', 'HPA', 'Hektopascal', 'hPa', 'Druck'),
    ('KMH', 'KMH', 'Kilometer/Stunde', 'km/h', 'Geschwindigkeit'),
    ('KMK', 'KMK', 'Kubikmeter/Kubikmeter', 'm^3/m^3', 'Volumenverhältnis'),
    ('KM2', 'KM2', 'Quadratkilometer', 'km^2', 'Fläche'),
    ('M/H', 'M/H', 'Meter/Stunde', 'm/h', 'Geschwindigkeit'),
    ('M/M', 'M/M', 'Meter/Minute', 'm/min', 'Geschwindigkeit'),
    ('M/S', 'M/S', 'Meter/Sekunde', 'm/s', 'Geschwindigkeit'),
    ('MMH', 'MMH', 'Millimeter/Stunde', 'mm/h', 'Geschwindigkeit'),
    ('MMS', 'MMS', 'Millimeter/Sekunde', 'mm/s', 'Geschwindigkeit'),
    ('MNM', 'MNM', 'Millinewton/Meter', 'mN/m', 'Oberflächenspannung'),
    ('MBZ', 'MBZ', 'Meterbar/Sekunde', 'm.bar/s', 'Staubexplosionskennz'),
    ('HR', 'HR', 'Stunde', 'h', 'dimensionslos'),
    ('K', 'K', 'Kelvin', 'K', 'Temperatur'),
    ('KA', 'KA', 'Kiloampere', 'kA', 'Elektr. Strom'),
    ('kbq', 'kbq', 'Kilobequerel', 'kBq', 'dimensionslos'),
    ('KHZ', 'KHZ', 'Kilohertz', 'kHz', 'Frequenz'),
    ('KJ', 'KJ', 'Kilojoule', 'kJ', 'Energie'),
    ('KN', 'KN', 'Kilonewton', 'kN', 'Kraft'),
    ('KOH', 'KOH', 'Kiloohm', 'kΩ', 'Elektr. Widerstand'),
    ('KPA', 'KPA', 'Kilopascal', 'kPa', 'Druck'),
    ('KV', 'KV', 'Kilovolt', 'kV', 'Elektr. Spannung'),
    ('KW', 'KW', 'Kilowatt', 'kW', 'Leistung'),
    ('KWH', 'KWH', 'Kilowattstunde', 'kWh', 'Energie'),
    ('V', 'V', 'Volt', 'V', 'Elektr. Spannung'),
    ('MIJ', 'MIJ', 'Millijoule', 'mJ', 'Energie'),
    ('MA', 'MA', 'Milliampere', 'mA', 'Elektr. Strom'),
    ('MBA', 'MBA', 'Millibar', 'mbar', 'Druck'),
    ('MF', 'MF', 'Millifarad', 'mF', 'Elektr. Kapazität'),
    ('MAV', 'MAV', 'Megavolt', 'MV', 'Elektr. Spannung'),
    ('MB', 'MB', 'Megabyte', 'MB', 'dimensionslos'),
    ('MIN', 'MIN', 'Minute', 'min', 'Zeit'),
    ('KMS', 'KMS', 'Kelvin/Sekunde', 'K/s', 'Temper.änderungsrate'),
    ('KMN', 'KMN', 'Kelvin/Minute', 'K/min', 'Temper.änderungsrate'),
    ('MN', 'MN', 'Meganewton', 'MN', 'Kraft'),
    ('%O', '%O', 'Promille', '‰', 'Verhältnis'),
    ('MEJ', 'MEJ', 'Megajoule', 'MJ', 'Energie'),
    ('MGO', 'MGO', 'Megaohm', 'MΩ', 'Elektr. Widerstand'),
    ('MGW', 'MGW', 'Megawatt', 'MW', 'Leistung'),
    ('MHZ', 'MHZ', 'Megahertz', 'MHz', 'Frequenz'),
    ('HZ', 'HZ', 'Hertz (1/Sekunde)', 'Hz', 'Frequenz'),
    ('VA', 'VA', 'Voltampere', 'VA', 'Leistung'),
    ('V%O', 'V%O', 'Volumenpromille', 'Vol.-%', 'Volumenverhältnis'),
    ('V%', 'V%', 'Volumenprozent', 'Vol.-%', 'Volumenverhältnis'),
    ('TS', 'TS', 'Tausend', '1000', 'dimensionslos'),
    ('JHR', 'JHR', 'Jahre', null, 'Zeit'),
    ('KVA', 'KVA', 'Kilovoltampere', 'kVA', 'Leistung'),
    ('LFM', 'LFM', 'lfm', null, 'dimensionslos'),
    ('M2', 'M2', 'Quadratmeter', 'm^2', 'Fläche'),
    ('NM', 'NM', 'Newton/Meter', 'N/m', 'Oberflächenspannung'),
    ('MON', 'MON', 'Monate', null, 'Zeit'),
    ('N1', 'N1', 'N1-pack', null, 'dimensionslos'),
    ('N2', 'N2', 'N2-Pack', null, 'dimensionslos'),
    ('N3', 'N3', 'N3-Pack', null, 'dimensionslos'),
    ('ONE', 'ONE', 'Eins', null, 'Verhältnis'),
    ('OP', 'OP', 'Originalpackung', null, 'dimensionslos'),
    ('PAA', 'PAA', 'Paar', null, 'dimensionslos'),
    ('PAK', 'PAK', 'Pack', null, 'dimensionslos'),
    ('PAL', 'PAL', 'Palette', null, 'dimensionslos'),
    ('PAT', 'PAT', 'Patienten', null, 'dimensionslos'),
    ('PCK', 'PCK', 'Päckchen', null, 'dimensionslos'),
    ('PKT', 'PKT', 'Punkte', null, 'Punkte'),
    ('PLT', 'PLT', 'Platte', null, 'dimensionslos'),
    ('VIA', 'VIA', 'VIAL', null, 'dimensionslos'),
    ('VL', 'VL', 'Versicherungsleistung', null, 'dimensionslos'),
    ('WCH', 'WCH', 'Wochen', null, 'Zeit'),
    ('L', 'L', 'Liter', 'l', 'Volumen'),
    ('ML', 'ML', 'Milliliter', 'ml', 'Volumen'),
    ('LT', 'LT', 'Liter', 'lt', 'Volumen'),
    ('µC', 'µC', 'Microcurie', 'µc', 'Volumen'),
    ('CM', 'CM', 'Zentimeter', 'cm', 'Länge'),
    ('DM', 'DM', 'Dezimeter', 'dm', 'Länge'),
    ('FT', 'FT', 'Fuß', 'ft', 'Länge'),
    ('G', 'G', 'Gramm', 'g', 'Masse'),
    ('MPZ', 'MPZ', 'Meterpascal/Sekunde', 'm.Pa/s', 'Staubexplosionskennz'),
    ('KG', 'KG', 'Kilogramm', 'kg', 'Masse'),
    ('KM', 'KM', 'Kilometer', 'km', 'Länge'),
    ('LB', 'LB', 'Pfund (Pound)', 'lb', 'Masse'),
    ('M', 'M', 'Meter', 'm', 'Länge'),
    ('MG', 'MG', 'Milligramm', 'mg', 'Masse'),
    ('MM', 'MM', 'Millimeter', 'mm', 'Länge'),
    ('YD', 'YD', 'Yard', 'yd', 'Länge'),
    ('µG', 'µG', 'Mikrogramm', 'µg', 'Masse'),
    ('µM', 'µM', 'Mikrometer', 'µm', 'Länge'),
    ('TO', 'TO', 'Tonne', 'to', 'Masse'),
    ('TON', 'TON', 'US-Tonne', 'ton', 'Masse'),
    ('UL', 'UL', 'Mikroliter', 'ul', 'Volumen'),
    ('µL', 'µL', 'Mikroliter', 'µl', 'Volumen'),
    ('YD3', 'YD3', 'Kubik Yard', 'yd3', 'Volumen'),
    ('MMG', 'MMG', 'Millimol/Gramm', 'mmol/g', 'Spez Äquivalentmenge'),
    ('µA', 'µA', 'Mikroampere', 'µA', 'Elektr. Strom'),
    ('nmo', 'nmo', 'Nanomol', 'nmol', 'dimensionslos'),
    ('KJK', 'KJK', 'Kilojoule/Kilogramm', 'kJ/kg', 'Spezifische Energie'),
    ('KD3', 'KD3', 'Kilogramm/Kubikdezimeter', 'kg/dm^3', 'Dichte'),
    ('KGV', 'KGV', 'Kilogramm/Kubikmeter', 'kg/m^3', 'Dichte'),
    ('GM3', 'GM3', 'Gramm/Kubikmeter', 'g/m^3', 'Dichte'),
    ('GM2', 'GM2', 'Gramm/Quadratmeter', 'g/m^2', 'Massenbedeckung'),
    ('KGF', 'KGF', 'Kilogramm/Quadratmeter', 'kg/m^2', 'Massenbedeckung'),
    ('MGG', 'MGG', 'Milligramm/Gramm', 'mg/g', 'Massenverhältnis'),
    ('MGK', 'MGK', 'Milligramm/Kilogramm', 'mg/kg', 'Massenverhältnis'),
    ('MGL', 'MGL', 'Milligramm/Liter', 'mg/l', 'Dichte'),
    ('µGL', 'µGL', 'Mikrogramm/Liter', 'µg/l', 'Dichte'),
    ('µGQ', 'µGQ', 'Mikrogramm/Kubikmeter', 'µg/m^3', 'Dichte'),
    ('GR', 'GR', 'Gramm', 'g', 'Masse'),
    ('LMI', 'LMI', 'Liter/Minute', 'l/min', 'Volumenstrom'),
    ('MS2', 'MS2', 'Meter/Quadratsekunde', 'm/s^2', 'Beschleunigung'),
    ('MM2', 'MM2', 'Quadratmillimeter', 'mm^2', 'Fläche'),
    ('µF', 'µF', 'Mikrofarad', 'µF', 'Elektr. Kapazität'),
    ('N', 'N', 'Newton', 'N', 'Kraft'),
    ('MPS', 'MPS', 'Millipascalsekunde', 'mPa.s', 'Zähigkeit, dynamisch'),
    ('MTE', 'MTE', 'Millitesla', 'mT', 'Magnet. Flußdichte'),
    ('MV', 'MV', 'Millivolt', 'mV', 'Elektr. Spannung'),
    ('MW', 'MW', 'Milliwatt', 'mW', 'Leistung'),
    ('MPB', 'MPB', 'Massen-parts per billion', 'ppb', 'Massenverhältnis'),
    ('VPB', 'VPB', 'Volumen-parts per billion', 'ppb', 'Volumenverhältnis'),
    ('MPM', 'MPM', 'Massen-parts per million', 'ppm', 'Massenverhältnis'),
    ('VPM', 'VPM', 'Volumen-parts per million', 'ppm', 'Volumenverhältnis'),
    ('MPT', 'MPT', 'Massen-parts per trillion', 'ppt', 'Massenverhältnis'),
    ('VPT', 'VPT', 'Volumen-parts per trillion', 'ppt', 'Volumenverhältnis'),
    ('MPA', 'MPA', 'Megapascal', 'MPa', 'Druck'),
    ('MVA', 'MVA', 'Megavoltampere', 'MVA', 'Leistung'),
    ('MWH', 'MWH', 'Megawattstunde', 'MWh', 'Energie'),
    ('PA', 'PA', 'Pascal', 'Pa', 'Druck'),
    ('OHM', 'OHM', 'Ohm', 'Ω', 'Elektr. Widerstand'),
    ('NA', 'NA', 'Nanoampere', 'nA', 'Elektr. Strom'),
    ('NF', 'NF', 'Nanofarad', 'nF', 'Elektr. Kapazität'),
    ('PF', 'PF', 'Pikofarad', 'pF', 'Elektr. Kapazität'),
    ('PAS', 'PAS', 'Pascalsekunde', 'Pa.s', 'Zähigkeit, dynamisch'),
    ('YD2', 'YD2', 'Quadrat Yard', 'yd^2', 'Fläche'),
    ('NAM', 'NAM', 'Nanometer', 'nm', 'Länge'),
    ('OZ', 'OZ', 'Unze', 'oz.', 'Masse'),
    ('BP', 'BP', 'Basenpaare', 'bp', 'dimensionslos'),
    ('BQL', 'BQL', 'Becquerel/Kilogramm', 'Bq/kg', 'Spez Akt radioak Sub'),
    ('CD', 'CD', 'Candela', 'cd', 'Lichtstärke'),
    ('CL', 'CL', 'Zentiliter', 'cl', 'Volumen'),
    ('ANZ', 'ANZ', 'Anzahl', null, 'dimensionslos'),
    ('HL', 'HL', 'Hektoliter', 'hl', 'Volumen'),
    ('F', 'F', 'Farad', 'F', 'Elektr. Kapazität'),
    ('FOZ', 'FOZ', 'Fluid Ounce US', 'US.fl.oz.', 'Volumen'),
    ('GAL', 'GAL', 'US-Gallone', 'gal.', 'Volumen'),
    ('GB', 'GB', 'Gigabyte', 'GB', 'dimensionslos'),
    ('GHG', 'GHG', 'Gramm/Hektogramm', 'g/hg', 'Massenverhältnis'),
    ('AP', 'AP', 'Anstaltpackung', null, 'dimensionslos'),
    ('BD', 'BD', 'Bund', null, 'dimensionslos'),
    ('BE', 'BE', 'Becher', null, 'dimensionslos'),
    ('BEH', 'BEH', 'Behälter', null, 'dimensionslos'),
    ('BL', 'BL', 'Blatt', null, 'dimensionslos'),
    ('BOX', 'BOX', 'Box', null, 'dimensionslos'),
    ('BST', 'BST', 'Bestimmungen', null, 'dimensionslos'),
    ('BTL', 'BTL', 'Beutel', null, 'dimensionslos'),
    ('BU', 'BU', 'Buch', null, 'dimensionslos'),
    ('DEG', 'DEG', 'Grad', null, 'dimensionslos'),
    ('DOS', 'DOS', 'Dosis', null, 'dimensionslos'),
    ('DRG', 'DRG', 'Dragee', null, 'dimensionslos'),
    ('DS', 'DS', 'Dose', null, 'dimensionslos'),
    ('DZ', 'DZ', 'Dutzend', null, 'dimensionslos'),
    ('EIM', 'EIM', 'Eimer', null, 'dimensionslos'),
    ('FAL', 'FAL', 'Fall / Patient', null, 'dimensionslos'),
    ('FL', 'FL', 'Flasche', null, 'dimensionslos'),
    ('FLT', 'FLT', 'Faltlage', null, 'dimensionslos'),
    ('FOL', 'FOL', 'Folie', null, 'dimensionslos'),
    ('FP', 'FP', '5er Pack', null, 'dimensionslos'),
    ('G/L', 'G/L', 'Gramm Wirkstoff / Liter', null, 'dimensionslos'),
    ('GAU', 'GAU', 'Gramm Gold', null, 'dimensionslos'),
    ('GF', 'GF', 'Gewichtungsfaktor REFX', null, 'dimensionslos'),
    ('GRO', 'GRO', 'Gross', null, 'dimensionslos'),
    ('GW', 'GW', 'Gramm Wirkstoff', null, 'dimensionslos'),
    ('GJ', 'GJ', 'Gigajoule', 'GJ', 'Energie'),
    ('GM', 'GM', 'Gramm/Mol', 'g/mol', 'Molmasse'),
    ('GKG', 'GKG', 'Gramm/Kilogramm', 'g/kg', 'Massenverhältnis'),
    ('GLI', 'GLI', 'Gramm/Liter', 'g/l', 'Dichte'),
    ('HA', 'HA', 'Hektar', 'ha', 'Fläche'),
    ('GOH', 'GOH', 'Gigaohm', 'GΩ', 'Elektr. Widerstand'),
    ('CMH', 'CMH', 'Zentimeter/Stunde', 'cm/h', 'Geschwindigkeit'),
    ('CMS', 'CMS', 'Zentimeter/Sekunde', 'cm/s', 'Geschwindigkeit'),
    ('H', 'H', 'Stunde', 'h', 'Zeit'),
    ('EML', 'EML', 'Einheiten Enzyme / Milliliter', 'U/ml', 'dimensionslos'),
    ('EE', 'EE', 'Einheiten Enzyme', 'U', 'dimensionslos'),
    ('22S', '22S', 'Quadratmillimeter/Sekunde', 'mm^2/s', 'Zähigkeit, kinemat.'),
    ('A', 'A', 'Ampere', 'A', 'Elektr. Strom'),
    ('ACR', 'ACR', 'Acre', 'acre', 'Fläche'),
    ('KGW', 'KGW', 'Kilogramm Wirkstoff', null, 'dimensionslos'),
    ('MI', 'MI', 'Meile', 'mi', 'Länge'),
    ('"', '"', 'Zoll (inch)', '"', 'Länge'),
    ('PT', 'PT', 'Pint, U.S. liquid', 'pt', 'Volumen'),
    ('QT', 'QT', 'Quart, U.S. liquid', 'qt', 'Volumen'),
    ('M3', 'M3', 'Kubikmeter', 'm3', 'Volumen'),
    ('MM3', 'MM3', 'Kubikmillimeter', 'mm3', 'Volumen'),
    ('MGQ', 'MGQ', 'Milligramm/Kubikmeter', 'mg/m^3', 'Dichte'),
    ('RHO', 'RHO', 'Gramm/Kubikzentimeter', 'g/cm^3', 'Dichte'),
    ('MGF', 'MGF', 'Milligramm/Quadratzentimeter', 'mg/cm^2', 'Massenbedeckung'),
    ('TOM', 'TOM', 'Tonne/Kubikmeter', 't/m^3', 'Dichte'),
    ('M3H', 'M3H', 'Kubikmeter/Stunde', 'm^3/h', 'Volumenstrom'),
    ('M3S', 'M3S', 'Kubikmeter/Sekunde', 'm^3/s', 'Volumenstrom'),
    ('MLK', 'MLK', 'Milliliter/Kubikmeter', 'ml/m^3', 'Volumenverhältnis'),
    ('TC3', 'TC3', '1/Kubikzentimeter', '1/cm^3', 'Teilchenkonzentratio'),
    ('TM3', 'TM3', '1/Kubikmeter', '1/m^3', 'Teilchenkonzentratio'),
    ('M2S', 'M2S', 'Quadratmeter/Sekunde', 'm^2/s', 'Zähigkeit, kinemat.'),
    ('NMM', 'NMM', 'Newton/Quadratmillimeter', 'N/mm^2', 'Druck'),
    ('mbq', 'mbq', 'Mikrobequerel', 'µBq', 'dimensionslos'),
    ('MIS', 'MIS', 'Mikrosekunde', 'µs', 'Zeit'),
    ('W', 'W', 'Watt', 'W', 'Leistung'),
    ('S', 'S', 'Sekunde', 'h', 'Zeit'),
    ('MS', 'MS', 'Millisekunde', 'ms', 'Zeit'),
    ('PPB', 'PPB', 'Parts per billion', 'ppb', 'Verhältnis'),
    ('PPM', 'PPM', 'Parts per million', 'ppm', 'Verhältnis'),
    ('PPT', 'PPT', 'Parts per trillion', 'ppt', 'Verhältnis'),
    ('NS', 'NS', 'Nanosekunde', 'ns', 'Zeit'),
    ('PS', 'PS', 'Pikosekunde', 'ps', 'Zeit'),
    ('STD', 'STD', 'Stunden', 'h', 'Zeit'),
    ('TP', 'TP', '10er', null, 'Pack-dimensionslos'),
    ('TES', 'TES', 'Tesla', 'T', 'Magnet. Flußdichte'),
    ('T', 'T', 'Tage', null, 'Zeit'),
    ('MI2', 'MI2', 'Quadratmeile', 'mi^2', 'Fläche'),
    ('PRS', 'PRS', 'Anzahl Personen', null, 'dimensionslos'),
    ('PTW', 'PTW', 'Punktwert', null, 'dimensionslos'),
    ('ROL', 'ROL', 'Rolle', null, 'dimensionslos'),
    ('RXN', 'RXN', 'Reaktionen', null, 'dimensionslos'),
    ('SA', 'SA', 'Satz', null, 'dimensionslos'),
    ('SET', 'SET', 'SET', null, 'dimensionslos'),
    ('ST', 'ST', 'Stück', null, 'dimensionslos'),
    ('STA', 'STA', 'Stab', null, 'dimensionslos'),
    ('TAG', 'TAG', 'Tage', null, 'Zeit'),
    ('TBL', 'TBL', 'Tabletten', null, 'dimensionslos'),
    ('TE', 'TE', 'Transfusionseinheiten', null, 'dimensionslos'),
    ('THE', 'THE', 'Therapieeinheiten', null, 'dimensionslos'),
    ('TR', 'TR', 'Trommel', null, 'dimensionslos')
;

--select * from metadata_repository.units;