drop table if exists gtds.auswertung_diz;
create table gtds.auswertung_diz(
  DATUM_DER_AUSWERTUNG       		 DATE   NOT NULL      ,
  SATZNUMMER                             INTEGER       ,
  PATIENTEN_ID                           VARCHAR(43) NOT NULL,
  ANZAHL_TUMOREN                         INTEGER    ,
  TUMOR_ID                               VARCHAR(2) NOT NULL ,
  GEBURTSDATUM                           DATE         ,
  STERBEDATUM                            DATE         ,
  STERBEDATUM_EXAKT                      VARCHAR(1)  ,
  GESCHLECHT                             VARCHAR(1)  ,
  PLZ                                    VARCHAR(20)       ,
  TUMORTOD                               VARCHAR(1)  ,
  AUTOPSIE                               VARCHAR(1)  ,
  AUFNAHMEDATUM                          DATE         ,
  DIAGNOSEDATUM                          DATE         ,
  DIAGNOSE_ABTEILUNG                     INTEGER   ,
  ANZAHL_ABTEILUNGEN                     SMALLINT    ,
  ABTEILUNG1                             INTEGER   ,
  ABTEILUNG2                             INTEGER   ,
  ABTEILUNG3                             INTEGER   ,
  ANZAHL_AERZTE                          SMALLINT    ,
  HAUSARZT                               INTEGER   ,
  ARZT1                                  INTEGER   ,
  ANZAHL_AUFENTHALTE                     SMALLINT    ,
  GESAMTDAUER_AUFENTHALTE                INTEGER    ,
  ICD9                                   VARCHAR(10) ,
  ICD10                                  VARCHAR(10) ,
  DIAGNOSETEXT                           VARCHAR(255),
  LOKALISATION                           VARCHAR(6)  ,
  LOKALISATION2                          VARCHAR(6)  ,
  LOK_SEITE                              VARCHAR(2)  ,
  LOK_AUFLAGE                            VARCHAR(2)  ,
  LOK_HAUPT_NEBEN                        VARCHAR(1)  ,
  ANZAHL_HISTOLOGIEN                     SMALLINT    ,
  HISTOLOGIE                             VARCHAR(10) ,
  HISTO_LFDNR                            SMALLINT    ,
  HISTO_AUFLAGE                          VARCHAR(2)  ,
  HISTO_HAUPT_NEBEN                      VARCHAR(1)  ,
  HISTO_DIAGNOSE                         VARCHAR(1)  ,
  HISTO_HERKUNFT                         VARCHAR(1)  ,
  HISTO_GRADING                          VARCHAR(2)  ,
  KLIN_TNM_LFDNR                         SMALLINT    ,
  KLIN_TNM_HERKUNFT                      VARCHAR(1)  ,
  KLIN_TNM_DATUM                         DATE         ,
  KLIN_P_T                               VARCHAR(1)  ,
  KLIN_T                                 VARCHAR(20) ,
  KLIN_P_N                               VARCHAR(1)  ,
  KLIN_N                                 VARCHAR(20) ,
  KLIN_P_M                               VARCHAR(1)  ,
  KLIN_MET                               VARCHAR(20) ,
  KLIN_TNM_AUFLAGE                       VARCHAR(5)  ,
  C_STADIUM                              VARCHAR(20) ,
  P_TNM_LFDNR                            SMALLINT   ,
  P_TNM_HERKUNFT                         VARCHAR(1)  ,
  P_TNM_DATUM                            DATE         ,
  P_P_T                                  VARCHAR(1)  ,
  P_T                                    VARCHAR(20) ,
  P_P_N                                  VARCHAR(1)  ,
  P_N                                    VARCHAR(20) ,
  P_P_M                                  VARCHAR(1)  ,
  P_MET                                  VARCHAR(20) ,
  P_TNM_AUFLAGE                          VARCHAR(5)  ,
  P_STADIUM                              VARCHAR(20) ,
  ANN_ARBOR_LFDNR                        SMALLINT    ,
  ANN_ARBOR_HERKUNFT                     VARCHAR(1)  ,
  ANN_ARBOR_DATUM                        DATE         ,
  ANN_ARBOR_STADIUM                      VARCHAR(5)  ,
  ANN_ARBOR_ALLGEMEIN                    VARCHAR(5)  ,
  ANZAHL_SONSTIGE                        SMALLINT    ,
  SONSTIGE_NAME                          VARCHAR(30) ,
  SONSTIGE_ID                            INTEGER    ,
  SONSTIGE_LFDNR                         SMALLINT    ,
  SONSTIGE_HERKUNFT                      VARCHAR(1)  ,
  SONSTIGE_DATUM                         DATE         ,
  SONSTIGE_STADIUM                       VARCHAR(10) ,
  THERAPIEEBEGINN                        DATE         ,
  PRIMAERTHERAPIE                        VARCHAR(255),
  ANZAHL_OPERATIONEN                     SMALLINT   ,
  OP_NUMMER                              SMALLINT    ,
  OP_DATUM                               DATE         ,
  OP_ABTEILUNG                           INTEGER  ,
  OP_BEZEICHNUNG                         VARCHAR(255),
  OP_SCHLUESSEL                          VARCHAR(15) ,
  OP_SCHLUESSEL_AUFLAGE                  VARCHAR(2)  ,
  ANZAHL_INNERE                          SMALLINT    ,
  INNERE_NUMMER                          SMALLINT    ,
  INNERE_BEGINN                          DATE         ,
  INNERE_ABTEILUNG                       INTEGER   ,
  INNERE_PROTOKOLL_ID                    INTEGER    ,
  INNERE_ANZAHL_ZYKLEN                   SMALLINT    ,
  INNERE_FREITEXT                        VARCHAR(255),
  ANZAHL_BESTRAHLUNGEN                   SMALLINT    ,
  BESTRAHLUNG_NUMMER                     SMALLINT    ,
  BESTRAHLUNG_DATUM                      DATE         ,
  BESTRAHLUNG_ABTEILUNG                  INTEGER   ,
  BESTRAHLUNG_FREITEXT                   VARCHAR(255),
  ANZAHL_TEILBESTRAHLUNGEN               SMALLINT    ,
  TEIL_BESTR_BEGINN                      DATE         ,
  ANZAHL_ZIELGEBIETE                     SMALLINT    ,
  ZIELGEBIET1                            VARCHAR(20) ,
  ZIELGEBIET2                            VARCHAR(20) ,
  APPLIKATIONSART                        VARCHAR(10) ,
  APPLIKATIONSTECHNIK                    VARCHAR(10) ,
  GESAMTDOSIS                            VARCHAR(10) ,
  GY_GBQ                                 VARCHAR(10) ,
  STRAHLENART                            VARCHAR(10) ,
  REFERENZ                               VARCHAR(5)  ,
  SONSTIGETHERAPIE                       VARCHAR(255),
  ERSTE_R_KLASSIFIKATION                 VARCHAR(5)  ,
  ERSTES_REZIDIV                         VARCHAR(20) ,
  DATUM_ERSTES_REZIDIV                   DATE         ,
  ANZAHL_NACHSORGEN                      SMALLINT   ,
  BEGINN_NACHSORGE                       DATE         ,
  LETZTE_NA_OHNE_PROGRESSION             DATE         ,
  ANZAHL_METASTASEN                      SMALLINT   ,
  DATUM_ERSTE_METASTASE                  DATE         ,
  METASTASE1                             VARCHAR(20) ,
  METASTASE2                             VARCHAR(20) ,
  ANZAHL_FOLGEERKRANKUNGEN               SMALLINT    ,
  FOLGEERKRANKUNG1                       VARCHAR(100),
  FOLGEERKRANKUNG2                       VARCHAR(100),
  LETZTE_INFO_DATENART                   VARCHAR(20) ,
  LETZTE_INFO_DATUM                      DATE         ,
  LETZTE_INFO_LFDNR                      INTEGER    ,
  OP_DURCHGEFUEHRT                       VARCHAR(255),
  REGISTER                               VARCHAR(5)  ,
  OP_INTENTION                           VARCHAR(1)  ,
  KLIN_TNM_AUSWERTUNGS_RELEVANT          VARCHAR(1)  ,
  P_TNM_AUSWERTUNGS_RELEVANT             VARCHAR(1)  ,
  DIAGNOSE_DF_ABT_ID                     INTEGER   ,
  DIAGNOSE_DF_ARZT_ID                    INTEGER   ,
  OP_DF_ABT_ID                           INTEGER   ,
  OP_DF_ARZT_ID                          INTEGER   ,
  INNERE_DF_ABT_ID                       INTEGER   ,
  INNERE_DF_ARZT_ID                      INTEGER   ,
  BESTRAHLUNG_DF_ABT_ID                  INTEGER   ,
  BESTRAHLUNG_DF_ARZT_ID                 INTEGER   ,
  INNERE_PROTOKOLL_TYP                   VARCHAR(20) ,
  ORTSKENNZAHL                           VARCHAR(10) ,
  TUMORFOLGENUMMER                       VARCHAR(5)  ,
  HISTOLOGIE2                            VARCHAR(10) ,
  KLIN_Y_SYMBOL                          VARCHAR(10) ,
  P_Y_SYMBOL                             VARCHAR(10) ,
  ANN_ARBOR_EXTRA                        VARCHAR(5)  ,
  SONSTIGE_KUERZEL                       VARCHAR(5)  ,
  THERAPIEENDE                           DATE         ,
  ALLE_OPERATIONEN                       VARCHAR(500),
  ALLE_INNEREN                           VARCHAR(500),
  ALLE_BESTRAHLUNGEN                     VARCHAR(500),
  LETZTE_R_KLASSIFIKATION                VARCHAR(5)  ,
  ANZAHL_R_KLASSIFIKATIONEN              VARCHAR(5)  ,
  ZEITPUNKT_TUMORFREIHEIT                DATE         ,
  TUMORFREIHEIT_VERLAUF                  SMALLINT    ,
  ALLE_FOLGEERKRANKUNGEN                 VARCHAR(500),
  ALLE_BEGLEITERKRANKUNGEN               VARCHAR(500),
  ALLE_METASTASEN                        VARCHAR(500),
  NAME                                   VARCHAR(4000) ,
  VORNAME                                VARCHAR(4000) ,
  ALLE_VORERKRANKUNGEN                   VARCHAR(500),
  LETZTER_STATUS_DATENART                VARCHAR(20) ,
  LETZTER_STATUS_DATUM                   DATE         ,
  LETZTE_STATUS_LFDNR                    INTEGER    ,
  LETZTER_STATUS                         VARCHAR(100),
  ALLE_ABTEILUNGEN                       VARCHAR(100),
  ALLE_AERZTE                            VARCHAR(100),
  KLIN_M                                 VARCHAR(5)  ,
  KLIN_L                                 VARCHAR(5)  ,
  KLIN_V                                 VARCHAR(5)  ,
  KLIN_S                                 VARCHAR(5)  ,
  P_M                                    VARCHAR(5)  ,
  P_L                                    VARCHAR(5)  ,
  P_V                                    VARCHAR(5)  ,
  P_S                                    VARCHAR(5)  ,
  ERSTES_LOK_REZIDIVDATUM                DATE         ,
  ERSTES_LOK_REZIDIVART                  VARCHAR(1)  ,
  ERSTES_LOK_REZIDIVVERLAUF              SMALLINT       ,
  KLIN_PNI                               VARCHAR(1)  ,
  P_PNI                                  VARCHAR(1)  ,
  KKR_EINWILLIGUNG                       VARCHAR(1)  ,
  BEHANDLUNGSANLASS                      VARCHAR(1)  ,
  ERFASSUNGSANLASS                       VARCHAR(1)  ,
  ARZT_ANLASS                            VARCHAR(1)  ,
  ZENTKENN                               VARCHAR(30) ,
  PRIMFALL                               VARCHAR(30) ,
  TRANSFORMATION_VERLAUF                 SMALLINT       ,
  TRANSFORMATION_DATUM                   DATE         ,
  TRANSFORMATION_HISTO_CODE              VARCHAR(10) ,
  TRANSFORMATION_HISTO_AUFLAGE           VARCHAR(10) ,
  ERSTE_LOKALE_RADIKALITAET              VARCHAR(10) ,
  DEFIN_LOKALE_RADIKALITAET              VARCHAR(10) ,
  DATUM_ERSTE_PROGRESSION                DATE         ,
  NACHFRAGEARZT                          INTEGER       ,
  HISTO_DATUM                            DATE         ,
  HISTO_SICHERUNGSDATUM                  DATE         ,
  DIAGSICH_HOECHSTE                      VARCHAR(1)  ,
  LETZTER_ABSCHLUSS_LFDNR                INTEGER       ,
  LETZTER_ABSCHLUSS_DATUM                DATE         ,
  LETZTER_ABSCHLUSS_GRUND                VARCHAR(1)  ,
  PLZ_BEI_DIAGNOSE                       VARCHAR(20)      ,
  VORANGEHENDE_DIAGNOSEN                 VARCHAR(255),
  GLEICHZEITIGE_DIAGNOSEN                VARCHAR(255),
  NACHFOLGENDE_DIAGNOSEN                 VARCHAR(255),
  KLIN_A_SYMBOL                          VARCHAR(1)  ,
  P_A_SYMBOL                             VARCHAR(1)  ,
  IARC_FLAG                              VARCHAR(255),
  OKZ_BEI_DIAGNOSE                       VARCHAR(10) ,
  DIAGNOSEDATUM_GENAU                    VARCHAR(1)  ,
  PRIMMETDATUM                           DATE         ,
  PRIMMETLOKS                            VARCHAR(255),
  SEKMETDATUM                            DATE         ,
  SEKMETLOKS                             VARCHAR(255),
  PRIMARY KEY(PATIENTEN_ID, TUMOR_ID)
);
